#include "gba.h"
#include "logic.h"
#include "draw.h"
// TA-TODO: Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
 #include "images/StartScreen.h"
 #include "images/character.h"
 #include "images/characterback.h"
 #include "images/characterright.h"
 #include "images/characterleft.h"
 #include "images/Xbackground.h"
 #include "images/Obackground.h"
 #include "images/Gameover.h"
 #include "images/Gamewon.h"
 #include "images/Temp_gameover.h"
 #include "images/Instructions.h"
 #include "images/Win_Animation.h"
 #include "images/WinScreen.h"

#include <stdio.h>
#include <stdlib.h>

// AppState enum definition
typedef enum {
    // TA-TODO: Add any additional states you need for your app.
    START,
    START_NODRAW,
    INSTRUCTIONS,
    APP_INIT,
    APP_RESET,
    APP,
    APP_EXIT,
    APP_RETRY_NODRAW,
    APP_WIN,
    APP_WIN_SCREEN,
    APP_EXIT_NODRAW,
} GBAState;


int main(void) {
    // TA-TODO: Manipulate REG_DISPCNT here to set Mode 3.
    REG_DISPCNT = MODE3 | BG2_ENABLE;

    GBAState state = START;

    // We store the "previous" and "current" states.
    AppState currentAppState, nextAppState;

    // We store the current and previous values of the button input.
    u32 previousButtons = BUTTONS;
    u32 currentButtons = BUTTONS;

    XO *exos = malloc(sizeof(XO) * 48);
    psnage *mainChar = malloc(sizeof(psnage));
    //row : start = 0, inc = 18
    //col : start = 30, inc = 40
    //--> 6*8 grid, x, y -->    0 + x*18,   30 + y*40
    //offset : x, y ==> (x*18), (x*18 + y)
    //offsetXO(x, y, 18) = x*18 + y

    unsigned short *saveArr = malloc(32*32);
    wimage *w = malloc(sizeof(wimage));

    while (1) {
        // Load the current state of the buttons
        currentButtons = BUTTONS;

        // TA-TODO: Manipulate the state machine below as needed.
        switch(state) {
            case START:
                // Wait for VBlank
                waitForVBlank();
                // TA-TODO: Draw the start state here.
                drawFullScreenImageDMA(StartScreen);

                state = START_NODRAW;
                break;
            case START_NODRAW:
                // TA-TODO: Check for a button press here to start the app.
                // Start the app by switching the state to APP_INIT.
                if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {
                    state = APP_INIT;
                }
                if (KEY_JUST_PRESSED(BUTTON_A, currentButtons, previousButtons)) {
                    state = INSTRUCTIONS;
                }
                break;
            case INSTRUCTIONS:
                // Wait for VBlank
                waitForVBlank();
                // TA-TODO: Draw the start state here.
                drawFullScreenImageDMA(Instructions);

                if (KEY_JUST_PRESSED(BUTTON_A, currentButtons, previousButtons)) {
                    state = START;
                }
                break;
            case APP_INIT:
                // Initialize the app. Switch to the APP state.

                currentAppState.exos = exos;
                currentAppState.mainChar = mainChar;
                currentAppState.saveArr = saveArr;
                currentAppState.w = w;
                initializeAppState(&currentAppState);
                //(currentAppState.exos + 1) -> isX = 0;

                // Draw the initial state of the app
                fullDrawAppState(&currentAppState);

                state = APP;
                //state = APP;
                break;
            case APP_RESET:
                // Initialize the app. Switch to the APP state.

                RE_initializeAppState(&currentAppState);
                //(currentAppState.exos + 1) -> isX = 0;

                // Draw the initial state of the app
                fullDrawAppState(&currentAppState);

                state = APP;
                //state = APP;
                break;
            case APP:
                // Process the app for one frame, store the next state
                nextAppState = processAppState(&currentAppState, previousButtons, currentButtons);

                // Wait for VBlank before we do any drawing.
                waitForVBlank();

                // Undraw the previous state
                undrawAppState(&currentAppState);

                // Draw the current state
                drawAppState(&nextAppState);

                // Now set the current state as the next state for the next iter.
                currentAppState = nextAppState;

                // Check if the app is exiting. If it is, then go to the exit state.
                if (nextAppState.gameOver) {
                    state = APP_EXIT;
                }

                if (nextAppState.onSnowUpdate) {
                    state = APP_RESET;
                }

                if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
                    state = START;
                }

                break;
            case APP_EXIT:
                // Wait for VBlank
                waitForVBlank();
                if(currentAppState.lives > 1 && !currentAppState.gameWon)//not actually game over, return to app & remove 1 life)
                {
                    currentAppState.lives--;
                    drawFullScreenImageDMA(Temp_gameover);
                    char hearts = 3;
                    for(int i = 0; i < currentAppState.lives; i++){
                        drawSpriteRight(90 + i*30-2, 70+2, hearts, COLOR(20,20,30));
                    }
                    for(int i = 0; i < currentAppState.lives; i++){
                        drawSpriteRight(90 + i*30, 70, hearts, COLOR(31,0,0));
                    }
                    for(int i = 0; i < currentAppState.lives; i++){
                        drawSpriteRight(90 + i*30, 70, 4, COLOR(20,0,0));
                    }
                    //draw temp gameover screen
                    state = APP_RETRY_NODRAW;
                } else if (!currentAppState.gameWon){
                    //draw gameover screen
                    drawFullScreenImageDMA(Gameover);
                    state = APP_EXIT_NODRAW;
                } else {
                    //drawFullScreenImageDMA(Gamewon);
                    state = APP_WIN;
                }
                // TA-TODO: Draw the exit / gameover screen
                break;
            case APP_RETRY_NODRAW:
                if (KEY_DOWN(BUTTON_START, currentButtons)) {
                    state = APP_RESET;
                    currentAppState.mainChar -> row = 0;
                    currentAppState.mainChar -> col = 0;
                    currentAppState.mainChar -> isFront = 1;
                    currentAppState.mainChar -> isSide = 0;
                }
                if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
                    state = START;
                }
                break;

            case APP_WIN:
                waitForVBlank();
                drawScrollDMA(currentAppState.w -> row, 0,
                        240, 160, 480, Win_Animation);
                while(currentAppState.w -> col < 240){
                    waitForVBlank();
                    if(vBlankCounter%2 == 0){
                        drawScrollDMA(currentAppState.w -> row, currentAppState.w -> col,
                        240, 160, 480, Win_Animation);
                        processAppStateWinScroll(&currentAppState);
                    }
                }
                processAppStateWinReset(&currentAppState);
                state = APP_WIN_SCREEN;
                break;

            case APP_WIN_SCREEN:
                processAppStateWin(&currentAppState, currentButtons);
                //full draw endscreen (make small version of endscreen)
                //use winScreenWalk (include files)
                waitForVBlank();
                undrawAppState(&currentAppState);
                drawWinState(&currentAppState);
                // if(currentAppState.wimageDraw) {
                //     drawFullScreenImageDMA(WinScreen);
                //     state = APP_EXIT_NODRAW;
                // }
                break;

            case APP_EXIT_NODRAW:
                // TA-TODO: Check for a button press here to go back to the start screen

                if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {
                    state = START;
                }
                if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
                    state = START;
                }
                break;
        }

        // Store the current state of the buttons
        previousButtons = currentButtons;
    }

    return 0;
}
